import { useEffect, useState } from "react";
import StatusBadge from "../components/StatusBadge";

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:5000";

function formatModifiedDate(value) {
  if (!value) {
    return "Unknown";
  }

  return new Date(value).toLocaleString();
}

function formatStatus(value) {
  return String(value || "Unknown")
    .replaceAll("_", " ")
    .toLowerCase()
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export default function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [advisorStatus, setAdvisorStatus] = useState(null);

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [advisorLoading, setAdvisorLoading] = useState(false);
  const [advisorMessage, setAdvisorMessage] = useState("");
  const [advisorError, setAdvisorError] = useState("");

  async function loadReports(signal) {
    try {
      setLoading(true);
      setError("");

      const response = await fetch(
        `${API_BASE_URL}/api/reports`,
        signal ? { signal } : undefined
      );

      if (!response.ok) {
        throw new Error(`Backend returned HTTP ${response.status}`);
      }

      const data = await response.json();

      setReports(
        Array.isArray(data.reports)
          ? data.reports
          : []
      );

      setAdvisorStatus(
        data.security_advisor || null
      );
    } catch (fetchError) {
      if (fetchError.name !== "AbortError") {
        console.error(
          "Failed to load reports:",
          fetchError
        );

        setError(
          "Unable to connect to the Reports API. " +
            "Start the Flask backend and refresh this page."
        );
      }
    } finally {
      if (!signal?.aborted) {
        setLoading(false);
      }
    }
  }

  useEffect(() => {
    const controller = new AbortController();

    loadReports(controller.signal);

    return () => controller.abort();
  }, []);

  async function generateSecurityAdvisor() {
    if (
      advisorLoading ||
      advisorStatus?.threat_analysis_required
    ) {
      return;
    }

    try {
      setAdvisorLoading(true);
      setAdvisorMessage("");
      setAdvisorError("");

      const generateUrl =
        advisorStatus?.generate_url ||
        "/api/security-advisor/generate";

      const response = await fetch(
        `${API_BASE_URL}${generateUrl}`,
        {
          method: "POST",
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.message ||
            `Security Advisor returned HTTP ${response.status}`
        );
      }

      setAdvisorMessage(
        `${data.message} ` +
          `${data.network_count ?? 0} network(s) reviewed, ` +
          `score ${data.overall_score ?? "Unknown"}/100, ` +
          `grade ${data.overall_grade ?? "Unknown"}.`
      );

      await loadReports();
    } catch (advisorRequestError) {
      console.error(
        "Security Advisor generation failed:",
        advisorRequestError
      );

      setAdvisorError(
        advisorRequestError.message ||
          "Security Advisor could not be generated."
      );

      await loadReports();
    } finally {
      setAdvisorLoading(false);
    }
  }

  function viewReport(report) {
    window.open(
      `${API_BASE_URL}${report.view_url}`,
      "_blank",
      "noopener,noreferrer"
    );
  }

  const advisorBlocked =
    Boolean(
      advisorStatus?.threat_analysis_required
    );

  return (
    <section className="appPage reportsPage">
      <div className="pageHeader">
        <span>Security Documentation</span>

        <h1>Reports</h1>

        <p>
          View and download security reports generated by the NetShield
          analysis modules.
        </p>
      </div>

      {!loading && !error && advisorStatus && (
        <div className="advisorGenerationPanel">
          <div className="advisorGenerationContent">
            <div>
              <span className="advisorGenerationLabel">
                Module 7
              </span>

              <h2>Security Advisor</h2>

              <p>
                Convert the current Threat Analysis report into clear
                explanations, recommendations, and an overall security
                grade.
              </p>
            </div>

            <div className="advisorGenerationStatus">
              <StatusBadge
                value={formatStatus(
                  advisorStatus.status
                )}
              />

              <span>
                {advisorStatus.message}
              </span>
            </div>
          </div>

          <div className="advisorGenerationActions">
            <button
              type="button"
              className="primaryButton"
              onClick={generateSecurityAdvisor}
              disabled={
                advisorLoading ||
                advisorBlocked
              }
            >
              {advisorLoading
                ? "Generating..."
                : "Generate Security Advisor"}
            </button>

            {advisorBlocked && (
              <p>
                Run fresh Threat Analysis in the Threat Center before
                generating Security Advisor recommendations.
              </p>
            )}

            {!advisorBlocked &&
              advisorStatus.generation_required && (
                <p>
                  Advisor generation is available for the current
                  Threat Analysis report.
                </p>
              )}

            {!advisorBlocked &&
              !advisorStatus.generation_required && (
                <p>
                  Security Advisor reports match the current Threat
                  Analysis.
                </p>
              )}
          </div>
        </div>
      )}

      {advisorMessage && (
        <p className="scannerActionMessage">
          {advisorMessage}
        </p>
      )}

      {advisorError && (
        <p className="scannerActionMessage errorMessage">
          {advisorError}
        </p>
      )}

      {!loading && !error && (
        <div className="reportsSummary">
          <span>Generated report files</span>
          <strong>{reports.length}</strong>
        </div>
      )}

      {loading && (
        <div className="networkTableMessage">
          Loading generated reports...
        </div>
      )}

      {!loading && error && (
        <div className="networkTableMessage errorMessage">
          {error}
        </div>
      )}

      {!loading && !error && reports.length === 0 && (
        <div className="networkTableMessage">
          No generated reports are currently available.
        </div>
      )}

      {!loading && !error && reports.length > 0 && (
        <div className="reportsGrid">
          {reports.map((report) => {
            const hasFreshness =
              Boolean(report.freshness_status);

            const reportIsStale =
              hasFreshness &&
              report.freshness_status !== "current";

            return (
              <div
                className="reportCard"
                key={report.filename}
              >
                <div className="docIcon">
                  <span></span>
                </div>

                <StatusBadge value={report.type} />

                <span className="reportCategory">
                  {report.category}
                </span>

                <h2>{report.title}</h2>

                <p>{report.description}</p>

                {hasFreshness && (
                  <div
                    className={`reportFreshness ${
                      reportIsStale
                        ? "reportFreshnessWarning"
                        : ""
                    }`}
                  >
                    <strong>
                      {formatStatus(
                        report.freshness_status
                      )}
                    </strong>

                    <span>
                      {report.freshness_message}
                    </span>
                  </div>
                )}

                <div className="reportMetadata">
                  <span>{report.filename}</span>
                  <span>{report.size}</span>
                  <span>
                    {formatModifiedDate(
                      report.modified_at
                    )}
                  </span>
                </div>

                <div className="reportActions">
                  <button
                    type="button"
                    onClick={() =>
                      viewReport(report)
                    }
                  >
                    {reportIsStale
                      ? "View Saved Report"
                      : "View Report"}
                  </button>

                  <a
                    href={`${API_BASE_URL}${report.download_url}`}
                    download
                  >
                    Download
                  </a>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
