import { useEffect, useState } from "react";
import StatusBadge from "../components/StatusBadge";

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:5000";

function formatModifiedDate(value) {
  if (!value) {
    return "Unknown";
  }

  return new Date(value).toLocaleString();
}

export default function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const controller = new AbortController();

    async function loadReports() {
      try {
        setLoading(true);
        setError("");

        const response = await fetch(`${API_BASE_URL}/api/reports`, {
          signal: controller.signal,
        });

        if (!response.ok) {
          throw new Error(`Backend returned HTTP ${response.status}`);
        }

        const data = await response.json();
        setReports(Array.isArray(data.reports) ? data.reports : []);
      } catch (fetchError) {
        if (fetchError.name !== "AbortError") {
          console.error("Failed to load reports:", fetchError);
          setError(
            "Unable to connect to the Reports API. Start the Flask backend and refresh this page."
          );
        }
      } finally {
        setLoading(false);
      }
    }

    loadReports();

    return () => controller.abort();
  }, []);

  function viewReport(report) {
    window.open(
      `${API_BASE_URL}${report.view_url}`,
      "_blank",
      "noopener,noreferrer"
    );
  }

  return (
    <section className="appPage reportsPage">
      <div className="pageHeader">
        <span>Security Documentation</span>
        <h1>Reports</h1>
        <p>
          View and download security reports generated by the NetShield
          analysis modules.
        </p>
      </div>

      {!loading && !error && (
        <div className="reportsSummary">
          <span>Generated report files</span>
          <strong>{reports.length}</strong>
        </div>
      )}

      {loading && (
        <div className="networkTableMessage">
          Loading generated reports...
        </div>
      )}

      {!loading && error && (
        <div className="networkTableMessage errorMessage">
          {error}
        </div>
      )}

      {!loading && !error && reports.length === 0 && (
        <div className="networkTableMessage">
          No generated reports are currently available.
        </div>
      )}

      {!loading && !error && reports.length > 0 && (
        <div className="reportsGrid">
          {reports.map((report) => (
            <div className="reportCard" key={report.filename}>
              <div className="docIcon">
                <span></span>
              </div>

              <StatusBadge value={report.type} />

              <span className="reportCategory">{report.category}</span>

              <h2>{report.title}</h2>
              <p>{report.description}</p>

              <div className="reportMetadata">
                <span>{report.filename}</span>
                <span>{report.size}</span>
                <span>{formatModifiedDate(report.modified_at)}</span>
              </div>

              <div className="reportActions">
                <button
                  type="button"
                  onClick={() => viewReport(report)}
                >
                  View Report
                </button>

                <a
                  href={`${API_BASE_URL}${report.download_url}`}
                  download
                >
                  Download
                </a>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}
